# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Product.create(name: "Ron Blanco Maddero")
Product.create(name: "Catedral Brut")
Product.create(name: "Bold Chocolate")
Product.create(name: "Cono Sur Brut")
Product.create(name: "Capel Especial 35°, 1.5 LTS.")
Product.create(name: "Cachaça 51")
Product.create(name: "Gran Torobayo")
Product.create(name: "G E Massenez")
Product.create(name: "Martini Bianco")
Product.create(name: "Martini Rosso")
Product.create(name: "Aperol")
Product.create(name: "Ramazzotti")
Product.create(name: "Parmesano pieza")
Product.create(name: "Pomidori Secchi")
Product.create(name: "De Nigris Glaze Classic Original")
Product.create(name: "Olive N11 Casa Rinaldi")
Product.create(name: "Nutella")
Product.create(name: "Schär Gluten Free Mix B Bread")
Product.create(name: "Divella Penne Rigate Senza Glutine")
Product.create(name: "Grissini Schär")
Product.create(name: "Polselli le Farine Speciali 25 Kg")
Product.create(name: "Polselli Sémola Rimacinata")
Product.create(name: "Polselli Sémola")
Product.create(name: "Kétchup Don Juan")
Product.create(name: "Salsa Barbacoa 1kg")
Product.create(name: "Ponte Nero Aceite de Oliva")
Product.create(name: "Champiñones bandeja")
Product.create(name: "Queso Mozzarella Barra Rumay")
Product.create(name: "Kunstman torobayo 500cc.")
Product.create(name: "Montes reserva merlot")
Product.create(name: "Rubezahl amber ale 330cc.")
Product.create(name: "Rubezahl session ipa")
Product.create(name: "7up zero 2lt.")
Product.create(name: "7 up 2 Lt.")
Product.create(name: "Agua mineral 6lt.")
Product.create(name: "Agua mineral con gas 1,6lt.")
Product.create(name: "Agua mineral panna 505ml")
Product.create(name: "Agua mineral s.pellegrino 505ml.")
Product.create(name: "Agua tonica botella 350 ml.")
Product.create(name: "Agua tonica lata 310ml.")
Product.create(name: "Bilz 350 ml.")
Product.create(name: "Canada dry lata 310ml.")
Product.create(name: "Canada dry zero lata 310ml.")
Product.create(name: "Coca cola normal 350ml.")
Product.create(name: "Coca cola light lata")
Product.create(name: "Fanta 350 ml.")
Product.create(name: "Jugo mango maracuya 1lt.")
Product.create(name: "Jugo piña guayaba 1lt.")
Product.create(name: "Nectar durazno 350 ml.")
Product.create(name: "Peroni")
Product.create(name: "Pap 350ml.")
Product.create(name: "Sanpellegrino aranciata")
Product.create(name: "Sanpellegrino aranciata rosa")
Product.create(name: "Sanpellegrino clementina")
Product.create(name: "Sanpellegrino limonata")
Product.create(name: "Sanpellegrino melograno y arancia")
Product.create(name: "Sanpellegrino pomelo")
Product.create(name: "Sprite 350ml.")
Product.create(name: "Aceite spray canola")
Product.create(name: "Aceite spray mantequilla")
Product.create(name: "Aceite vegetal 1lt.")
Product.create(name: "Bombilla papel 400un.")
Product.create(name: "Servilleta 14x14 500 un.")
Product.create(name: "Toalla de baño 207mt.")
Product.create(name: "Toalla jumbo 150 mt.")
Product.create(name: "Toalla nova 100 hojas")
Product.create(name: "Ajo en polvo 100gr.")
Product.create(name: "Albahaca deshidratada 6gr.")
Product.create(name: "Clavo de olor 5gr.")
Product.create(name: "Coco rallado 100gr.")
Product.create(name: "Jenjibre molido 15gr.")
Product.create(name: "Oregano entero 250gr.")
Product.create(name: "Polvo de hornear 750gr.")
Product.create(name: "Romero deshidratado 10gr.")
Product.create(name: "Atun 160gr.")
Product.create(name: "Choritos 190gr.")
Product.create(name: "Machas 425gr.")
Product.create(name: "Papayas al jugo 1000gr.")
Product.create(name: "Sal fina 1kg.")
Product.create(name: "Vinagre incoloro 500ml.")
Product.create(name: "Aerosol desinfectante")
Product.create(name: "Cera roja 530cm.")
Product.create(name: "Cloro 4lt.")
Product.create(name: "Desengrasante 1lt.")
Product.create(name: "Esponja")
Product.create(name: "Lavalozas 500cc")
Product.create(name: "Queso mozzarella chilolac")
Product.create(name: "Queso azul")
Product.create(name: "Queso vegano")
Product.create(name: "Queso crema")
Product.create(name: "Azucar flor 1kg.")
Product.create(name: "Cafe descafeinado")
Product.create(name: "Palitos de masa")
Product.create(name: "Vaso de carton")
Product.create(name: "Vaso plastico 500cc.")
Product.create(name: "Crema de leche 1lt.")
Product.create(name: "Leche entera 1lt.")
Product.create(name: "Bandeja de champiñon ostra")
Product.create(name: "Bandeja de champiñon portobello")
Product.create(name: "Bolsa de champiñones")
Product.create(name: "Bandeja de champiñon shitake")
Product.create(name: "Bandeja de endibia")
Product.create(name: "Bolsa de albahaca")
Product.create(name: "Bolsa de menta")
Product.create(name: "Bolsa de rúcula")
Product.create(name: "Bolsa espinaca")
Product.create(name: "Caja de moron congelado 1kg.")
Product.create(name: "Frambuesa congelada 1kg.")
Product.create(name: "Levadura fresca 500gr.")
Product.create(name: "Malla de limón sutil")
Product.create(name: "Mango")
Product.create(name: "Piña")
Product.create(name: "Pulpa de mango 1kg.")
Product.create(name: "Pulpa de maracuya 1kg.")
Product.create(name: "Pulpa chirimoya")
Product.create(name: "Mix berries")
Product.create(name: "Pulpa de frutilla")
Product.create(name: "Pulpa de piña 1kg.")
Product.create(name: "Chorizo español")
Product.create(name: "Salame")
Product.create(name: "Jamón colonial")
Product.create(name: "Tocino")
Product.create(name: "Cera")
Product.create(name: "Desengrasante")
Product.create(name: "Detergente")
Product.create(name: "Guante latex azul 100un.")
Product.create(name: "Jabon liquido")
Product.create(name: "Lavalozas")
Product.create(name: "Limpia pisos")
Product.create(name: "Limpia vidrios")
Product.create(name: "Alusa")
Product.create(name: "Papel aluminio")
Product.create(name: "Virutilla ollas")
Product.create(name: "Alto del carmen especial 750 cc.")
Product.create(name: "Ballantines 1Lt")
Product.create(name: "Bombay 750ml")
Product.create(name: "Cachaza")
Product.create(name: "Campari")
Product.create(name: "Duval curacao blue")
Product.create(name: "Espumante catedral")
Product.create(name: "Espumante cono sur")
Product.create(name: "Vodka eristof")
Product.create(name: "Espumante rose cono sur")
Product.create(name: "Goma")
Product.create(name: "Granadina")
Product.create(name: "Tequila catrina")
Product.create(name: "Johnnie walker red label 1 lt.")
Product.create(name: "Late harvest concha y toro")
Product.create(name: "Licor de manzana verde")
Product.create(name: "Martini extra dry 750ml.")
Product.create(name: "Mitjans triple sec")
Product.create(name: "Mitjans amaretto")
Product.create(name: "Mitjans cassis")
Product.create(name: "Mitjans licor de cacao")
Product.create(name: "Petirrojo reserva cabernet sauvignon")
Product.create(name: "Petirrojo reserva chardonnay")
Product.create(name: "Petirojo sauvignon blanc")
Product.create(name: "Pisco capel 1,5 lt")
Product.create(name: "Pisco mistral 1 Lt.")
Product.create(name: "Pisco mistral 750 cc.")
Product.create(name: "Ron blanco maddero")
Product.create(name: "Sandy mar 700 cc")
Product.create(name: "Veramonte reserva organico carmenere")
Product.create(name: "Veramonte reserva organico merlot")
Product.create(name: "Sauvignon blanc veramonte")
Product.create(name: "Chardonay veramonte")
Product.create(name: "Azúcar vergnano x 800")
Product.create(name: "Chocolate vergnano 1kg")
Product.create(name: "Endulzante vergnano x 1000")
Product.create(name: "Espresso clasico vergnano 1kg.")
Product.create(name: "Aceite vegetal 3lt.")
Product.create(name: "Manitoba 3 kg.")
Product.create(name: "Aceite de oliva 5 Lt.")
Product.create(name: "Harina Perla 25kg.")
Product.create(name: "Premix marraqueta 25kg.")
Product.create(name: "Concentrado tomate")
Product.create(name: "Crema tartufa")
Product.create(name: "Pesto")
Product.create(name: "Pomodoro o dolcissima")
Product.create(name: "Aceitunas")
Product.create(name: "Aceitunas mediterraneas")
Product.create(name: "Alcachofa")
Product.create(name: "Nutella 3kg.")
Product.create(name: "Palmitos")
Product.create(name: "Pimiento morron")
Product.create(name: "Tomate deshidratado")
Product.create(name: "Pimiento tiritas")
Product.create(name: "Nduja 1,3 kg")
Product.create(name: "Jamón serrano o prosciutto")
Product.create(name: "Aceto")
Product.create(name: "Bolsa papel")
Product.create(name: "Caja blanca pizza 33x33x3")
Product.create(name: "Caja blanca pizza 40x40x4")
Product.create(name: "Caja cafe pizza 38x38")
Product.create(name: "Caja carton chica")
Product.create(name: "Caja carton maxi")
Product.create(name: "Caja carton normal")
Product.create(name: "Cuchara de madera 100 un.")
Product.create(name: "Cuchillo de madera 100 un.")
Product.create(name: "Envase cartón para pastas")
Product.create(name: "Envase plastico chessecake")
Product.create(name: "Envase plastico salsa")
Product.create(name: "Envase waffle")
Product.create(name: "Tenedor de madera 100 un.")
Product.create(name: "Vaso desechable cafe vergnano 80mm")
Product.create(name: "Vaso plastico 500cc.")
Product.create(name: "Ketchup 900 gr.")
Product.create(name: "Miel")
Product.create(name: "Mostaza 900 gr")
Product.create(name: "Mayonesa")
Product.create(name: "Salsa bbq 1kg.")
Product.create(name: "Arandanos 1kg")
Product.create(name: "Bolsa de pechuga de pollo")
Product.create(name: "Camaron 36/40 1kg.")
Product.create(name: "Choclo 1kg.")
Product.create(name: "Frambuesas 1kg.")
Product.create(name: "Hamburguesa")
Product.create(name: "Mozzarella perline 1kg.")
Product.create(name: "Ostion 1kg.")
Product.create(name: "Papas prefritas 5KG.")
Product.create(name: "Pastelera de choclo 1kg.")
Product.create(name: "Pepperoni laminado 5,67kg.")
Product.create(name: "Piezas de salmon")
Product.create(name: "Pimientos asados")
Product.create(name: "Pulpa de piña 1kg.")
Product.create(name: "Ricotta 2kg.")
Product.create(name: "Tutitos bbq")
Product.create(name: "Comandas")
Product.create(name: "Papel mantequilla x 1000 hojas")
Product.create(name: "Servilleta 14x14 500 un.")
Product.create(name: "Servilleta coctail 23x22,5 200 un.")
Product.create(name: "Toalla 320mt.")
Product.create(name: "Toalla interfoliada")
Product.create(name: "Toalla jumbo 150 mt.")
Product.create(name: "Coca Cola Zero 350 ml")
Product.create(name: "Peroni")
Product.create(name: "Cerveza Corona")
Product.create(name: "Canadá Dry Ginger Ale 350 ml")
Product.create(name: "Canadá Dry Ginger Ale Zero 310 ml")
Product.create(name: "Canadá Dry Agua Tónica 310 ml")
Product.create(name: "Canadá Dry Agua Tónica Zero 310 ml")
Product.create(name: "Austral Calafate")
Product.create(name: "Austral Lager")
Product.create(name: "Kunstmann Sin Alcohol")
Product.create(name: "Pap Lata 350 ml")
Product.create(name: "Espárragos")
Product.create(name: "Canadá Dry Agua Tónica Lata 350 ml")
Product.create(name: "Petirrojo Carmenere")
Product.create(name: "Ramazzotti Violetto")
Product.create(name: "Pulpa Frambueza")